### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by dholler** [confcompass/ti-simple-xmpp#1]
Hi, 
first of all i'd like to thank you for the effort you did put into this project.

I'm trying to include an xmpp client into my app project, but can't get it running. Whenever I try to connect the client via xmpp.connect() the app crashes. I could figure it down till the Session.call() call inside the Client constructor on line 709 of ti-simple-xmpp.js.
Is this a known issue or did I just missed something?

I've installed the module via gittio install, if that matters.

Any help would be appreciated.

Greetings from Germany,
nos

**Comment by svanderburg** [comment]
It's a bit difficult to say what the source of the problem is. Can you show me the function invocation (and parameters) that you are using to connect?

And does this problem occur on iOS, Android, or both?

**Comment by dholler** [comment]
```
module.exports = function () {
    var xmpp = require('ti-simple-xmpp').SimpleXMPP;

    xmpp.on('online', function(data) {
        console.log('Connected with JID: ' + data.jid.user);
        console.log('Yes, I\'m connected!');
    });

    xmpp.on('chat', function(from, message) {
        xmpp.send(from, 'echo: ' + message);
    });

    xmpp.on('error', function(err) {
        console.error(err);
    });

    xmpp.on('subscribe', function(from) {
        if (from === 'a.friend@gmail.com') {
            xmpp.acceptSubscription(from);
        }
    });

    this.connect = function(credentials){
        xmpp.connect({
            websocket: { url: credentials.host },
            jid : credentials.username + '@' + credentials.domain,
            password : credentials.password,
            reconnect: true,
            skipPresence: false
        });
    };

    // // check for incoming subscription requests
    // xmpp.getRoster();

    return this;
};

```

This is the class I use to get the client running.
On iOS it crashes while executing the xmpp.connect().
I can give you the device error log if you found that useful.

Meanwhile on android the app keeps running but logs:

> {"type":"error","source":{"bubbleParent":true,"apiName":"Ti.Proxy","_events":{"open":{},"close":{},"error":{},"message":{}}},"advice":"reconnect","bubbles":false,"error":"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference","cancelBubble":false}

right after it tries to connect as I'd guess.

Edit:
After diving deeper into the code, I found that it crashes at about line 70 while executing the ws.open:

```
this.ws = tiws.createWS();
var url = arguments[0];
this.ws.open(url);
```

So it seems to be an issue with the tiws module. Any idea?

Meanwhile: Including your module it throws upon starting the app:

> [ERROR] : Script Error {
> [ERROR] :      column = 35;
> [ERROR] :      line = 3779;
> [ERROR] :      message = "Object prototype may only be an Object or null.";
> [ERROR] :      sourceURL = "file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js";
> [ERROR] :      stack = "create@[native code]\ninherits@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:3779:35\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:26510:14\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:27334:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:28253:35\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:28265:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:28300:26\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:11463:24\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:11554:8\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:23989:26\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:23746:19\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:23793:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:10286:44\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:6421:21\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:6811:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:3012:23\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:2963:25\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1618:19\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1823:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:558:22\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:990:8\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:544:21\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:84:19\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:866\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:55:29\no@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:818\ne@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:1461\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:1478\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:210\nfile:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:1:449\nglobal code@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/ti-simple-xmpp.js:29430:70\nrequire@[native code]\nexports@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/be/service/MessengerService.js:2:23\ngetMessengerService@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/be/service/ServiceFactory.js:32:36\nglobal code@file:///var/containers/Bundle/Application/171BC31F-51B0-4B86-A622-1A6BE7240117/AFA%20App.app/app.js:42:63";
> [ERROR] : }

Maybe this leads to the final crash.

Gonna try a clean project an look if it has something todo with my current app state.

**Comment by svanderburg** [comment]
What happens if you add the following parameter to the `xmpp.connect()` invocation?

``` json
preferred: 'PLAIN'
```

It seems there is something odd with the underlying websockets library on iOS.

**Comment by dholler** [comment]
Yeah.
First of all: My server didn't support websockets.
Second: If websockets arn't supported the tiws module just crashes.

I'll close this issue for now, because I'm pretty sure a new server will fix that.

Thanks for your time.

Greetings.
